### ISSUE TITLE
MIDIOSC grid emulation for use with monome-rack

### ISSUE THREAD

**Issue by jpnielsen** [SitStayCreate/midiosc#1]
Please see 

https://community.vcvrack.com/t/monome-modules-thread/3683/62

I hope you can get your software to work with monome-rack. I'm looking forward to run it on my 15.3" Android 8 tablet controlling VCV rack + monome-rac on windows 11,

**Comment by jpnielsen** [comment]
MIDIOSC reply has "sii"  in it 

I think it should be ssi

https://monome.org/docs/serialosc/osc/#:~:text=/serialosc/device%20ssi%20%3Cid%3E%20%3Ctype%3E%20%3Cport%3E

**Comment by SitStayCreate** [comment]
Hi there,

Thank you for calling this to my attention. There definitely is a bug here that you have found.

I am looking through the source and I do not see sii in the code. I am sending a string that is composed of numerals (i.e. "64" or "128" - sorry if this is not clear) and it might be that this is being coerced into sii by the other application. The relevant code is in the file RequestServer.java.

I am using the dimensions of the device for the second OSC argument. I do not own a monome device, so was using an arbitrary value because it did not seem to matter with the serialosc patch in Max 7. I can change this to the appropriate String if you can provide me with that info/or if I can find it on lines forum. Do you know what the arguments would look like on a standard 128 grid?

**Comment by jpnielsen** [comment]
About the source - Is it possible for me to build it from scratch from what
is on the github ? - I know next to nothing about java and maven. Could you
possibly write instructions on how to build and install ?

I read about OSC - "sii" means that the parameters following are type
"string", "integer", "integer"
I don't know for a fact, but I think it is "m128", plus "-###" incremented
for each device connected (or random) - I have seen "m128-388" in logs.

**Comment by jpnielsen** [comment]
Thank you very much!

**Comment by SitStayCreate** [comment]
I consulted the docs here: https://monome.org/docs/grid/studies/max/. It looks like the String "monome <area of grid>" is sent as the second argument. I understand now you were referring to the ID (1st) and not the Type (2nd) argument. After reading this and thinking it over, it seems likely in your case that adding the word monome in front of the number will prevent this data from being coerced to an int, if that is in fact what is happening. I'm willing to make this change since it seems to be consistent across both grids and arcs, but will continue researching.

**Comment by SitStayCreate** [comment]
I have added the fix in version 1.1.01. Please let me know if it is working for you.

**Comment by jpnielsen** [comment]
It's not connecting.

I'm thinking the monome plugin is expecting something else than "ssc-01"

But I can't really understand the source 

https://github.com/Dewb/monome-rack/blob/3338724501bd77fc9ef550d9e028f5ad845f459a/lib/serialosc/SerialOsc.cpp#L333

**Comment by SitStayCreate** [comment]
Good find there - that looks promising. The thing is, I don't think this other program's logic is correct as far as I understand the monome OSC scheme. I believe when I was designing midiosc I found a post by Brian Crabtree explaining that the numbers do reflect the model of monome you are using, however it would be complicated to explain and by extension probably use meaningfully in a monome patch or standalone app. I'll try to find that post if I can since I'm sure it's on their forum under tehn.

I think the type string informs the app what kind of device it is and what size it should be. As evidence of this, notice in the grid studies documentation https://monome.org/docs/grid/studies/max/ that serialosc never reflects this naming scheme. It also does not with a monome arc https://monome.org/docs/serialosc/setup/.

I have more work to do on midiosc - it is affected by log4j and I would recommend against using it until I can rebuild the JavaOSC library and repackage it with my own version, so I'll keep your issue open and try to work with you on it as time permits.

**Comment by SitStayCreate** [comment]
https://llllllll.co/t/monome-device-id-guide/16277/10 This I think is the thread I tried to use to understand how to build midiosc. I think reading it now, I find it just as difficult as I did the first time I read it. There might be something else at play here, before serialosc there was monomeserial and I believe it used a different format. Are you sure this app wasn't built with serialosc in mind and not monomeserial?

It looks like someone else had the same question I have and did not receive a response: https://llllllll.co/t/possible-types-reported-by-serialosc-server/1301

**Comment by jpnielsen** [comment]
I'm quite sure it wants to connect to "serialosc" on port 12002 - and I can
see the communication in a network sniffer on the loopback interface.

But I'm not sure it knows of all monome devices - new and old.

The developer has said that it's not his priority to make virtual grids
work right now.

**Comment by jpnielsen** [comment]
Here's the communication:

```
280	42.137570	127.0.0.1	127.0.0.1	LLC	88	S, func=RNR, N(R)=55; DSAP 0x22 Group, SSAP 0x62 Command

0000   02 00 00 00 45 00 00 54 da 46 00 00 80 11 00 00   ....E..T.F......
0010   7f 00 00 01 7f 00 00 01 f8 25 2e e2 00 40 cb 0e   .........%...@..
0020   23 62 75 6e 64 6c 65 00 00 00 00 00 00 00 00 01   #bundle.........
0030   00 00 00 24 2f 73 65 72 69 61 6c 6f 73 63 2f 6c   ...$/serialosc/l
0040   69 73 74 00 2c 73 69 00 31 32 37 2e 30 2e 30 2e   ist.,si.127.0.0.
0050   31 00 00 00 00 00 32 c8                           1.....2.

281	42.137717	127.0.0.1	127.0.0.1	LLC	92	S, func=RNR, N(R)=55; DSAP 0x22 Group, SSAP 0x62 Command

0000   02 00 00 00 45 00 00 58 da 47 00 00 80 11 00 00   ....E..X.G......
0010   7f 00 00 01 7f 00 00 01 f8 26 2e e2 00 44 56 98   .........&...DV.
0020   23 62 75 6e 64 6c 65 00 00 00 00 00 00 00 00 01   #bundle.........
0030   00 00 00 28 2f 73 65 72 69 61 6c 6f 73 63 2f 6e   ...(/serialosc/n
0040   6f 74 69 66 79 00 00 00 2c 73 69 00 31 32 37 2e   otify...,si.127.
0050   30 2e 30 2e 31 00 00 00 00 00 32 c8               0.0.1.....2.

282	42.143021	127.0.0.1	127.0.0.1	UDP	84	63527 → 13000 Len=52

0000   02 00 00 00 45 00 00 50 da 48 00 00 80 11 00 00   ....E..P.H......
0010   7f 00 00 01 7f 00 00 01 f8 27 32 c8 00 3c 23 ed   .........'2..<#.
0020   2f 73 65 72 69 61 6c 6f 73 63 2f 64 65 76 69 63   /serialosc/devic
0030   65 00 00 00 2c 73 73 69 00 00 00 00 73 73 63 2d   e...,ssi....ssc-
0040   30 31 00 00 6d 6f 6e 6f 6d 65 20 31 32 38 00 00   01..monome 128..
0050   00 00 2e e2                                       ....

283	42.143257	127.0.0.1	127.0.0.1	LLC	72	S, func=RNR, N(R)=55; DSAP 0x22 Group, SSAP 0x62 Command

0000   02 00 00 00 45 00 00 44 da 49 00 00 80 11 00 00   ....E..D.I......
0010   7f 00 00 01 7f 00 00 01 f8 28 2e e2 00 30 63 46   .........(...0cF
0020   23 62 75 6e 64 6c 65 00 00 00 00 00 00 00 00 01   #bundle.........
0030   00 00 00 14 2f 73 79 73 2f 69 6e 66 6f 00 00 00   ..../sys/info...
0040   2c 69 00 00 00 00 32 c8                           ,i....2.

284	42.143359	127.0.0.1	127.0.0.1	LLC	76	S, func=RNR, N(R)=55; DSAP 0x22 Group, SSAP 0x62 Command

0000   02 00 00 00 45 00 00 48 da 4a 00 00 80 11 00 00   ....E..H.J......
0010   7f 00 00 01 7f 00 00 01 f8 29 2e e2 00 34 4c bb   .........)...4L.
0020   23 62 75 6e 64 6c 65 00 00 00 00 00 00 00 00 01   #bundle.........
0030   00 00 00 18 2f 73 79 73 2f 70 72 65 66 69 78 00   ..../sys/prefix.
0040   2c 73 00 00 72 61 63 6b 00 00 00 00               ,s..rack....

285	42.143438	127.0.0.1	127.0.0.1	LLC	72	S, func=RNR, N(R)=55; DSAP 0x22 Group, SSAP 0x62 Command

0000   02 00 00 00 45 00 00 44 da 4b 00 00 80 11 00 00   ....E..D.K......
0010   7f 00 00 01 7f 00 00 01 f8 2a 2e e2 00 30 5d 31   .........*...0]1
0020   23 62 75 6e 64 6c 65 00 00 00 00 00 00 00 00 01   #bundle.........
0030   00 00 00 14 2f 73 79 73 2f 70 6f 72 74 00 00 00   ..../sys/port...
0040   2c 69 00 00 00 00 32 c8                           ,i....2.
```

**Comment by SitStayCreate** [comment]
https://monome.org/docs/grid/editions/ I think I understand what is going on here now. There are different edition monome grids that use one of three protocols - 40h, series, and mext. Midiosc will not work with apps written for 40h or series, only mext. The other app is looking for 40h and series devices. There's another Java app called pages that will work with 40h and series. I used to use this before I built midiosc to work with mext apps. I tried to find a link for you on lines, but I couldn't find one. If you post there, somebody might have a copy or know of the current location of the repo or whatever. I'm going to mark the issue as closed since I built this in 2020 and those protocols were already deprecated by then. I'm sorry I couldn't help you, but good luck.

**Comment by BjarneJensen** [comment]
@jpnielsen Did you ever figure this out?

**Comment by BjarneJensen** [comment]
Virtual grid and launchpad sync for me when I set the port to 13000 for vcv rack, however I get this error when I press a button `"Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Not a valid OSC address: rack/grid/key"` any ideas @SitStayCreate?
